on:
  push:

jobs:
  get-version:
    uses: shiipou/github-actions/.github/workflows/get-version.yml@main
    with:
      release-branches: '^(main)$'

  build:
    name: Spring build
    runs-on: ubuntu-latest

    needs:
      - get-version
    steps:
      - name: print version
        run: echo "${{ needs.get-version.outputs.version }}"
      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - run: ls -lia target

  release:
    name: Create Release
    needs: build
    if: ${{ needs.get-version.outputs.will-release }}
    uses: shiipou/github-actions/.github/workflows/_release-ci.yml@main
    with:
      version: ${{ needs.get-version.outputs.version }}
